name: Database Migration

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      #Restore Depndencies
      - name: Restore dependencies
        run: dotnet restore
      #Install Entity Framework Core
      - name: Install EF
        run: dotnet tool install --global dotnet-ef
      #Update database with migration also specifying the solution and project file to use for the update
      - name: Update Database with Migration
        run: dotnet-ef database update --connection '${{ secrets.SQL_CONNECTION_STRING  }}' -s MusicAdventureAPI/MusicAdventureAPI.csproj -p MAData/MAData.csproj
